#!/bin/sh -eu
#
# Connect to BitcoinWisdom web socket and display rates real time

while sleep 60; do
    # Produce ping command to the web socket stream every minute
    echo say ping >&2
    echo ping
done |
    wscat --connect 'https://d2.bitcoinwisdom.com/?symbol=bitfinexbtcusd' |
    # Ugly colors in wscat output, get only the payload
    sed -urn 's/^> .\[2K.\[E.\[34m< (.*).\[39m$/\1/p' |
    # Get last trade in a packet and get its price
    stdbuf -oL jq 'select(.type=="trades") | .trades | last | .price' |
    while read -r price; do
	convert -background white -gravity center +antialias +dither \
		-font Ubuntu -pointsize 6 -define pango:markup=false \
                "pango:`printf "$ %.2f" $price`" \
                -gravity north -crop '40x7+1+1!' -threshold 50% \
                -flatten /tmp/hinta.png
	echo got trade $price >&2
    done
