#!/bin/sh -eu
#
# Send any 40x7 frame to Telepulssi

# Set serial port parameters if outputting to a char device
test -c $1 && stty -F $1 raw 9600

# Pad every LED segment with 3 pixels bar at the end with ImageMagick
# and make it black and white only.
convert "$1" -background white +dither -gravity northwest \
	-crop '40x7+0+0!' -threshold 50% -flatten \
	-splice 3x0+40+0 -splice 3x0+35+0 -splice 3x0+30+0 \
	-splice 3x0+25+0 -splice 3x0+20+0 -splice 3x0+15+0 \
	-splice 3x0+10+0 -splice 3x0+5+0 -flatten "mono:$2"
