#!/bin/sh -eu
#
# Fade given text in on Telepulssi

. "`dirname $0`/common.sh"

# Fade given text in
for i in `seq 0 50`; do
    sleep 0.05&
    render_text "$2" $i
    wait
done | send_to_screen "$1"
