#!/bin/sh -eu
#
# Send any 40x7 frame to Telepulssi

. "`dirname $0`/common.sh"

convert "$1" -background white +dither -gravity northwest \
	-crop '40x7+0+0!' -threshold 50% $byte_padding_magick mono:- |
    send_to_screen "$2"
